name: ${project.name}
main: net.daboross.bukkitdev.commandtimer.CommandTimer
version: ${project.version}
author: Dabo Ross
description: Newlanders Command Timer
commands:
   refreshtimer:
     description: This manually runs the command timer
     usage: /<command>
     permission: commandtimer.refreshtimer
